### ISSUE TITLE
unable to build indicators

### ISSUE THREAD

**Issue by nesper8** [hcsubser/hybridbar#6]
trying to build indicators returns with error even after installing hybridbar
```
meson.build:24:0: ERROR: Dependency "hybridbar-1.0" not found, tried pkgconfig and cmake
```
full log trying to build with ./build.sh 
[build.log](https://github.com/hcsubser/hybridbar/files/6500113/build.log)

**Comment by hcsubser** [comment]
What distribution is this on? And what prefix did you set when compiling hybridbar?
It is saying that it cannot find hybridbar-1.0.pc file which is generally located under $PREFIX/$LIB/pkg-config.

If you just ran 'meson build' to compile then prefix is /usr/local and on Ubuntu or Debian that pkg-config file will be under /usr/local/lib/x86_64-linux-gnu/pkg-config on arch and I believe Fedora it will be under /usr/local/lib64/pkg-config.

If your prefix is for example /opt/hybridbar then it will be located here:
Ubuntu,Debian:/opt/hybridbar/lib/x86_64-linux-gnu
Fedora,Arch:/opt/hybridbar/lib64/pkg-config
you get the idea.

what you have to do, because meson and pkgconfig do not seem to be able to find that hybridbar-1.0.pc file you have to find the folder that it is located in yourself and run ./build.sh like this:
`
  PKG_CONFIG_PATH=/path/to/lib/pkg-config ./build.sh
`
NOTE:Path to folder that .pc file is located in, not the file itself

**Comment by nesper8** [comment]
Closing cuz I was able to build successfully after parsing --prefix=/usr on meson
